### ISSUE TITLE
M1 mac run ld -o HelloWorld HelloWorld.o  error!

### ISSUE THREAD

**Issue by wangyuan02605** [Apress/programming-with-64-bit-ARM-assembly-language#5]
Hi,
I want to know how to slove this problem
Undefined symbols for architecture arm64:
  "_main", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture arm64
 and i want to know whether you run HelloWorld in rosetta 
Thanks~

**Comment by wangyuan02605** [comment]
sorry I get it !
ld -o HelloWorld HelloWorld.o \
	-lSystem \
	-syslibroot `xcrun -sdk macosx --show-sdk-path` \
	-e _start \
	-arch arm64

**Comment by below** [comment]
If you want to find all the samples for the M1, I have a repository for you: https://github.com/below/HelloSilicon
